server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
